# Generated by Django 4.2 on 2025-09-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOLCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('carrier_name', models.CharField(max_length=200, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['carrier_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('company_name', models.CharField(default='Cincinnati Barge & Rail Terminal, LLC', max_length=200)),
                ('address_line1', models.CharField(default='1707 Riverside Drive', max_length=200)),
                ('address_line2', models.CharField(default='Cincinnati, Ohio 45202', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.CharField(default='www.BARGE2RAIL.com', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo_text', models.CharField(default='CBR', max_length=10)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Company Branding',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('customer', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_tons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('truck_number', models.CharField(max_length=50)),
                ('trailer_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='bol_system.carrier')),
            ],
            options={
                'ordering': ['truck_number'],
                'unique_together': {('carrier', 'truck_number')},
            },
        ),
        migrations.CreateModel(
            name='BOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('bol_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('buyer_name', models.CharField(max_length=200)),
                ('ship_to', models.TextField()),
                ('customer_po', models.CharField(blank=True, max_length=100)),
                ('carrier_name', models.CharField(max_length=200)),
                ('truck_number', models.CharField(max_length=50)),
                ('trailer_number', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('net_tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('created_by_email', models.CharField(default='system@primetrade.com', max_length=200)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_system.carrier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bol_system.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol_system.product')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bol_system.truck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
