# Generated by manual migration for Release models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('release_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('customer_id_text', models.CharField(max_length=200)),
                ('customer_po', models.CharField(blank=True, max_length=100)),
                ('ship_via', models.CharField(blank=True, max_length=200)),
                ('fob', models.CharField(blank=True, max_length=200)),
                ('ship_to_name', models.CharField(blank=True, max_length=200)),
                ('ship_to_street', models.CharField(blank=True, max_length=200)),
                ('ship_to_city', models.CharField(blank=True, max_length=100)),
                ('ship_to_state', models.CharField(blank=True, max_length=2)),
                ('ship_to_zip', models.CharField(blank=True, max_length=10)),
                ('lot', models.CharField(blank=True, max_length=100)),
                ('material_description', models.CharField(blank=True, max_length=200)),
                ('quantity_net_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('OPEN','Open'),('COMPLETE','Complete'),('CANCELLED','Cancelled')], default='OPEN', max_length=12)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ReleaseLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('seq', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('planned_tons', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING','Pending'),('SHIPPED','Shipped'),('CANCELLED','Cancelled')], default='PENDING', max_length=12)),
                ('bol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bol_system.bol')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='bol_system.release')),
            ],
            options={'ordering': ['seq']},
        ),
        migrations.AlterUniqueTogether(
            name='releaseload',
            unique_together={('release','seq')},
        ),
    ]