# Generated by manual migration for CustomerShipTo, Lot, and Release FK fields
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0002_releases'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerShipTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_tos', to='bol_system.customer')),
            ],
            options={'ordering': ['customer','name']},
        ),
        migrations.AlterUniqueTogether(
            name='customershipto',
            unique_together={('customer','street','city','state','zip')},
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('c', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('si', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('s', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('p', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('mn', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bol_system.product')),
            ],
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='release',
            name='carrier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bol_system.carrier'),
        ),
        migrations.AddField(
            model_name='release',
            name='customer_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bol_system.customer'),
        ),
        migrations.AddField(
            model_name='release',
            name='lot_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bol_system.lot'),
        ),
        migrations.AddField(
            model_name='release',
            name='ship_to_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bol_system.customershipto'),
        ),
    ]