# Generated by migration for product chemistry + last_lot_code
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0003_customer_shipto_lot_and_release_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_lot_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='c',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='si',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='s',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
