# Generated by migration for AuditLog
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0004_product_chemistry_fields.py'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('action', models.CharField(max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('user_email', models.CharField(blank=True, max_length=200)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
