# Generated by migration for DB indexes on Release, ReleaseLoad, and BOL
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0005_auditlog'),
    ]

    operations = [
        # Release(status, created_at)
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['status', 'created_at'], name='release_status_created_idx'),
        ),
        # ReleaseLoad(status) and (release_id, status)
        migrations.AddIndex(
            model_name='releaseload',
            index=models.Index(fields=['status'], name='releaseload_status_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseload',
            index=models.Index(fields=['release', 'status'], name='releaseload_release_status_idx'),
        ),
        # BOL(product_id), BOL(date), BOL(customer_id)
        migrations.AddIndex(
            model_name='bol',
            index=models.Index(fields=['product'], name='bol_product_idx'),
        ),
        migrations.AddIndex(
            model_name='bol',
            index=models.Index(fields=['date'], name='bol_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bol',
            index=models.Index(fields=['customer'], name='bol_customer_idx'),
        ),
    ]
