# Generated by Django 4.2 on 2025-10-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0006_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bol',
            name='bol_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='bol',
            name='bol_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='bol',
            name='bol_customer_idx',
        ),
        migrations.RemoveIndex(
            model_name='release',
            name='release_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='releaseload',
            name='releaseload_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='releaseload',
            name='releaseload_release_status_idx',
        ),
    ]
