# Generated by Django 4.2 on 2025-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0007_remove_bol_bol_product_idx_remove_bol_bol_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseload',
            name='actual_tons',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual tonnage from BOL (replaces planned_tons when shipped)', max_digits=10, null=True),
        ),
    ]
