# Generated by Django 4.2 on 2025-11-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0008_releaseload_actual_tons'),
    ]

    operations = [
        migrations.AddField(
            model_name='customershipto',
            name='street2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='release',
            name='ship_to_street2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
