# Generated by Django 4.2 on 2025-11-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0009_add_street2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='lot_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to lot for chemistry data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bol_system.lot'),
        ),
        migrations.AddField(
            model_name='bol',
            name='release_number',
            field=models.CharField(blank=True, help_text='Release number for reference', max_length=20),
        ),
    ]
