# Generated by Django 4.2 on 2025-11-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0010_add_lot_and_release_to_bol'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special warehouse/BOL requirements (e.g., Material #, delivery instructions, tarping, etc.)'),
        ),
    ]
