# Generated by Django 4.2 on 2025-11-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0011_add_special_instructions_to_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special warehouse/BOL requirements from release'),
        ),
    ]
