# Generated by Django 4.2 on 2025-11-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0012_add_special_instructions_to_bol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
