# Generated by Django 4.2 on 2025-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0013_add_customer_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='official_weight_entered_at',
            field=models.DateTimeField(blank=True, help_text='When official weight was entered', null=True),
        ),
        migrations.AddField(
            model_name='bol',
            name='official_weight_entered_by',
            field=models.CharField(blank=True, help_text='User who entered official weight', max_length=200),
        ),
        migrations.AddField(
            model_name='bol',
            name='official_weight_tons',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Certified scale weight (official)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bol',
            name='weight_variance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage variance', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bol',
            name='weight_variance_tons',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference between official and CBRT scale', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bol',
            name='net_tons',
            field=models.DecimalField(decimal_places=2, help_text='CBRT scale weight (estimate)', max_digits=10),
        ),
    ]
