# Generated by Django 4.2 on 2025-11-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0014_add_official_weight_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL to customer's logo image", max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_color',
            field=models.CharField(blank=True, default='#2563eb', help_text='Primary brand color (hex code, e.g., #2563eb)', max_length=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_color',
            field=models.CharField(blank=True, default='#667eea', help_text='Secondary brand color (hex code, e.g., #667eea)', max_length=7),
        ),
    ]
