# Generated by Django 4.2 on 2025-11-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0015_customer_logo_url_customer_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bol',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
