# Generated by Django 4.2 on 2025-11-06 17:58

from django.db import migrations, models


def create_initial_redirects(apps, schema_editor):
    """Create initial role redirect configurations"""
    RoleRedirectConfig = apps.get_model('bol_system', 'RoleRedirectConfig')

    # Create default redirects for each role
    RoleRedirectConfig.objects.bulk_create([
        RoleRedirectConfig(
            role_name='viewer',
            landing_page='/client.html?productId=9',
            is_active=True
        ),
        RoleRedirectConfig(
            role_name='read only',
            landing_page='/client.html?productId=9',
            is_active=True
        ),
        RoleRedirectConfig(
            role_name='user',
            landing_page='/',
            is_active=True
        ),
        RoleRedirectConfig(
            role_name='admin',
            landing_page='/',
            is_active=True
        ),
    ])


def reverse_initial_redirects(apps, schema_editor):
    """Remove initial role redirect configurations"""
    RoleRedirectConfig = apps.get_model('bol_system', 'RoleRedirectConfig')
    RoleRedirectConfig.objects.filter(
        role_name__in=['viewer', 'read only', 'user', 'admin']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0016_increase_pdf_url_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRedirectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='Role name: viewer, read-only, user, admin', max_length=20, unique=True)),
                ('landing_page', models.CharField(help_text='URL to redirect to (e.g., /client.html?productId=9)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Disable to use default redirect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Redirect Configuration',
                'verbose_name_plural': 'Role Redirect Configurations',
                'ordering': ['role_name'],
            },
        ),
        migrations.RunPython(create_initial_redirects, reverse_initial_redirects),
    ]
