# Generated by Django 4.2 on 2025-11-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0017_roleredirectconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseload',
            name='actual_tons',
        ),
    ]
