# Generated by Django 4.2 on 2025-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0019_remove_actual_tons_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='stamped_pdf_url',
            field=models.URLField(blank=True, help_text='Watermarked PDF with official weight stamp', max_length=1000),
        ),
    ]
