# Generated by Django 4.2 on 2025-11-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0020_add_stamped_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='care_of_co',
            field=models.CharField(blank=True, default='PrimeTrade, LLC', help_text="Company name for 'c/o' line in BOL Ship From section (copied from release)", max_length=200),
        ),
        migrations.AddField(
            model_name='release',
            name='care_of_co',
            field=models.CharField(blank=True, default='PrimeTrade, LLC', help_text="Company name for 'c/o' line in BOL Ship From section (for blind shipping)", max_length=200),
        ),
    ]
