# Generated by Django 5.2.8 on 2025-12-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bol_system", "0022_bol_pdf_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full tenant name (e.g., 'Liberty Steel')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., 'LIBERTY')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this audit log belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="bol_system.tenant",
            ),
        ),
        migrations.AddField(
            model_name="bol",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this BOL belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bols",
                to="bol_system.tenant",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this carrier belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carriers",
                to="bol_system.tenant",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this customer belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="bol_system.tenant",
            ),
        ),
        migrations.AddField(
            model_name="customershipto",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this ship-to belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ship_tos",
                to="bol_system.tenant",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this lot belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="bol_system.tenant",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this product belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="bol_system.tenant",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this release belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releases",
                to="bol_system.tenant",
            ),
        ),
        migrations.AddField(
            model_name="releaseload",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this release load belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="release_loads",
                to="bol_system.tenant",
            ),
        ),
    ]
