# Generated by Django 5.2.8 on 2025-12-05 14:50

from django.db import migrations


def create_liberty_tenant_and_assign(apps, schema_editor):
    """
    Create LIBERTY tenant and assign all existing data to it.
    """
    Tenant = apps.get_model('bol_system', 'Tenant')
    Product = apps.get_model('bol_system', 'Product')
    Customer = apps.get_model('bol_system', 'Customer')
    CustomerShipTo = apps.get_model('bol_system', 'CustomerShipTo')
    Carrier = apps.get_model('bol_system', 'Carrier')
    BOL = apps.get_model('bol_system', 'BOL')
    Lot = apps.get_model('bol_system', 'Lot')
    Release = apps.get_model('bol_system', 'Release')
    ReleaseLoad = apps.get_model('bol_system', 'ReleaseLoad')
    AuditLog = apps.get_model('bol_system', 'AuditLog')

    # Create LIBERTY tenant
    liberty, created = Tenant.objects.get_or_create(
        code='LIBERTY',
        defaults={'name': 'Liberty Steel', 'is_active': True}
    )

    # Assign all existing records to LIBERTY
    Product.objects.filter(tenant__isnull=True).update(tenant=liberty)
    Customer.objects.filter(tenant__isnull=True).update(tenant=liberty)
    CustomerShipTo.objects.filter(tenant__isnull=True).update(tenant=liberty)
    Carrier.objects.filter(tenant__isnull=True).update(tenant=liberty)
    BOL.objects.filter(tenant__isnull=True).update(tenant=liberty)
    Lot.objects.filter(tenant__isnull=True).update(tenant=liberty)
    Release.objects.filter(tenant__isnull=True).update(tenant=liberty)
    ReleaseLoad.objects.filter(tenant__isnull=True).update(tenant=liberty)
    AuditLog.objects.filter(tenant__isnull=True).update(tenant=liberty)


def reverse_migration(apps, schema_editor):
    """
    Reverse: Set all tenant FKs back to null (don't delete tenant).
    """
    Product = apps.get_model('bol_system', 'Product')
    Customer = apps.get_model('bol_system', 'Customer')
    CustomerShipTo = apps.get_model('bol_system', 'CustomerShipTo')
    Carrier = apps.get_model('bol_system', 'Carrier')
    BOL = apps.get_model('bol_system', 'BOL')
    Lot = apps.get_model('bol_system', 'Lot')
    Release = apps.get_model('bol_system', 'Release')
    ReleaseLoad = apps.get_model('bol_system', 'ReleaseLoad')
    AuditLog = apps.get_model('bol_system', 'AuditLog')

    Product.objects.all().update(tenant=None)
    Customer.objects.all().update(tenant=None)
    CustomerShipTo.objects.all().update(tenant=None)
    Carrier.objects.all().update(tenant=None)
    BOL.objects.all().update(tenant=None)
    Lot.objects.all().update(tenant=None)
    Release.objects.all().update(tenant=None)
    ReleaseLoad.objects.all().update(tenant=None)
    AuditLog.objects.all().update(tenant=None)


class Migration(migrations.Migration):
    dependencies = [
        ("bol_system", "0023_add_tenant_fk_to_models"),
    ]

    operations = [
        migrations.RunPython(create_liberty_tenant_and_assign, reverse_migration),
    ]
