# Generated by Django 5.2.8 on 2025-12-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0024_set_existing_data_to_liberty_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, help_text='Email address from SSO (must match exactly)', max_length=254)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary customer shown on dashboard (only one per user)')),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'View & Edit'), ('admin', 'Full Access')], default='view', help_text='Level of access to customer data', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.EmailField(blank=True, help_text='Admin who granted this access', max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this access grant')),
                ('customer', models.ForeignKey(help_text='Customer this user can access', on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='bol_system.customer')),
                ('tenant', models.ForeignKey(help_text='Tenant this access belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customer_access', to='bol_system.tenant')),
            ],
            options={
                'verbose_name': 'User Customer Access',
                'verbose_name_plural': 'User Customer Access',
                'ordering': ['user_email', '-is_primary', 'customer__customer'],
                'indexes': [models.Index(fields=['user_email', 'is_primary'], name='bol_system__user_em_36f518_idx')],
                'unique_together': {('user_email', 'customer')},
            },
        ),
    ]
