# Generated by Django 5.2.8 on 2025-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0025_user_customer_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('tenant', 'release_number')},
        ),
    ]
