# Generated by Django 5.2.8 on 2026-01-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0026_release_number_per_tenant_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='bol_date',
            field=models.DateField(blank=True, help_text='BOL date as proper DateField', null=True),
        ),
        migrations.AddField(
            model_name='bol',
            name='chemistry_display',
            field=models.CharField(blank=True, help_text='Formatted chemistry at issuance', max_length=200),
        ),
        migrations.AddField(
            model_name='bol',
            name='is_void',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bol',
            name='issued_by',
            field=models.CharField(blank=True, help_text='User who issued this BOL', max_length=200),
        ),
        migrations.AddField(
            model_name='bol',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Snapshot at issuance - do not update', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bols', to='bol_system.lot'),
        ),
        migrations.AddField(
            model_name='bol',
            name='release_display',
            field=models.CharField(blank=True, help_text='"123-1" format for search/PDF', max_length=30),
        ),
        migrations.AddField(
            model_name='bol',
            name='release_line',
            field=models.ForeignKey(blank=True, help_text='The release load this BOL fulfills', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bols', to='bol_system.releaseload'),
        ),
        migrations.AddField(
            model_name='bol',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bol',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bol',
            name='voided_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bolcounter',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this counter belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bol_counters', to='bol_system.tenant'),
        ),
        migrations.AddField(
            model_name='releaseload',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when BOL created', null=True),
        ),
        migrations.AlterField(
            model_name='bol',
            name='bol_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bol',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bol',
            name='lot_ref',
            field=models.ForeignKey(blank=True, help_text='Legacy lot reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bols_legacy', to='bol_system.lot'),
        ),
        migrations.AlterField(
            model_name='bol',
            name='release_number',
            field=models.CharField(blank=True, help_text='Legacy release number for reference', max_length=20),
        ),
        migrations.AlterField(
            model_name='bolcounter',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lot',
            name='code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='releaseload',
            name='bol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_loads_legacy', to='bol_system.bol'),
        ),
        migrations.AlterUniqueTogether(
            name='bol',
            unique_together={('tenant', 'bol_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bolcounter',
            unique_together={('tenant', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='bol',
            index=models.Index(fields=['tenant', 'bol_date'], name='bol_system__tenant__1accfb_idx'),
        ),
        migrations.AddIndex(
            model_name='bol',
            index=models.Index(fields=['tenant', 'is_void'], name='bol_system__tenant__aa66d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='bol',
            constraint=models.UniqueConstraint(condition=models.Q(('is_void', False)), fields=('release_line',), name='uniq_active_bol_per_release_line'),
        ),
    ]
