# Generated by Django 5.2.8 on 2026-01-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0027_primetrade_integration_session1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='bol_status',
            field=models.CharField(choices=[('created', 'Created'), ('ready', 'Ready for Pickup'), ('signed', 'Signed')], db_index=True, default='created', help_text='Kiosk workflow status', max_length=20),
        ),
        migrations.AddField(
            model_name='bol',
            name='signature',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG signature'),
        ),
        migrations.AddField(
            model_name='bol',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bol',
            name='signed_by',
            field=models.CharField(blank=True, help_text='Driver name who signed', max_length=100),
        ),
    ]
