# Generated by Django 5.2.8 on 2026-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0028_kiosk_driver_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Configuration name for reference', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active config is used for sending emails')),
                ('to_emails', models.TextField(help_text='Primary recipients (one email per line)')),
                ('cc_emails', models.TextField(blank=True, help_text='CC recipients (one email per line)')),
                ('enabled', models.BooleanField(default=True, help_text='Uncheck to disable all BOL notification emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Notification Config',
                'verbose_name_plural': 'Email Notification Configs',
            },
        ),
    ]
