# Generated by Django 5.2.8 on 2026-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0028_kiosk_driver_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='chemistry_override_acknowledged',
            field=models.BooleanField(default=False, help_text='User acknowledged chemistry differs from existing lot'),
        ),
        migrations.AddField(
            model_name='release',
            name='chemistry_override_at',
            field=models.DateTimeField(blank=True, help_text='When override was acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='chemistry_override_by',
            field=models.CharField(blank=True, help_text='User who acknowledged the override', max_length=200),
        ),
        migrations.AddField(
            model_name='release',
            name='chemistry_override_reason',
            field=models.TextField(blank=True, help_text='Reason for chemistry override (optional)'),
        ),
    ]
