# Generated by Django 5.2.8 on 2026-01-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0029_add_chemistry_override_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='chemistry_override_c',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Override Carbon value for this release', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='chemistry_override_mn',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Override Manganese value for this release', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='chemistry_override_p',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Override Phosphorus value for this release', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='chemistry_override_s',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Override Sulfur value for this release', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='chemistry_override_si',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Override Silicon value for this release', max_digits=6, null=True),
        ),
    ]
