# Generated by Django 5.2.8 on 2026-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0030_add_release_chemistry_override_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='system', max_length=200)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable BOL notification emails')),
                ('to_emails', models.TextField(default='lbryant@primetradeusa.com', help_text='Primary recipients (one email per line)')),
                ('cc_emails', models.TextField(default='orders@primetradeusa.com\ntraffic@barge2rail.com', help_text='CC recipients (one email per line)')),
            ],
            options={
                'verbose_name': 'Email Notification Settings',
                'verbose_name_plural': 'Email Notification Settings',
            },
        ),
    ]
