# Generated by Django 5.2.8 on 2026-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol_system', '0032_rename_tenant_to_primetrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(help_text="Short code (e.g., 'PRT')", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text="Full tenant name (e.g., 'PrimeTrade')", max_length=100),
        ),
    ]
