# Generated by Django 5.2.8 on 2026-01-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('truck_number', models.CharField(blank=True, max_length=50)),
                ('visit_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('ready', 'Ready'), ('signed', 'Signed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('bol_id', models.IntegerField(blank=True, null=True)),
                ('bol_number', models.CharField(blank=True, max_length=50)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'indexes': [models.Index(fields=['code'], name='kiosk_drive_code_a40244_idx'), models.Index(fields=['status', 'checked_in_at'], name='kiosk_drive_status_c54296_idx')],
            },
        ),
    ]
