# Generated by Django 5.2.8 on 2026-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_kiosk_driver_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversession',
            name='carrier_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='driversession',
            name='pickup_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driversession',
            name='trailer_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='truck_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='visit_type',
            field=models.CharField(blank=True, default='pickup', max_length=20),
        ),
    ]
